dist: xenial
os: linux
language: python
services:
    - docker

before_install:
    - docker pull python
    - docker run -t -d --name=testenv python

install:
    - docker exec testenv apt update
    - docker exec testenv apt upgrade -y
    - docker exec testenv apt install -y python-pip
    - docker exec testenv pip install flake8 pytest
before_script:
    - docker cp ./ testenv:/
    - docker exec testenv pip install -r requirements.txt
    - docker exec testenv python --version
script:
    - docker exec testenv flake8 main.py --ignore W503,W504 --max-line-length 210
notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze-testwiki"
      - "chat.freenode.net##RhinosF1"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
